"""
打印任务切片服务。

优先执行外部切片命令；可通过环境变量开启 mock gcode 兜底。
"""

from __future__ import annotations

import asyncio
import json
import math
import re
import shlex
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import urlparse

import aiohttp

from config import Config
from logger import logger
from utils.oss_util import oss_manager


class PrintSliceError(RuntimeError):
    """切片失败。"""


def _build_client_download_name(job_id: str, original_name: str) -> str:
    """
    给 client 下发唯一文件名，避免打印机端反复上传同名 plate_1.gcode
    被 Moonraker 视为“文件正在使用”而拒绝覆盖。
    """
    suffix = Path(original_name or "").suffix or ".gcode"
    return f"{job_id}{suffix}"


def _parse_duration_to_seconds(raw_value: str) -> Optional[int]:
    text = raw_value.strip()
    if not text:
        return None
    if text.isdigit():
        return int(text)

    total = 0
    matched = False
    for value, unit in re.findall(r"(\d+)\s*([dhms])", text.lower()):
        matched = True
        number = int(value)
        if unit == "d":
            total += number * 86400
        elif unit == "h":
            total += number * 3600
        elif unit == "m":
            total += number * 60
        elif unit == "s":
            total += number
    return total if matched else None


def _load_slice_result_metadata(output_dir: Path) -> Dict[str, Any]:
    candidates = [output_dir / Config.PRINT_SLICER_RESULT_FILE_NAME]
    fallback_result = output_dir / "result.json"
    if fallback_result not in candidates:
        candidates.append(fallback_result)

    for result_file in candidates:
        if not result_file.exists():
            continue
        try:
            data = json.loads(result_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise PrintSliceError(f"切片结果文件无法解析: {result_file}") from exc
        if not isinstance(data, dict):
            raise PrintSliceError(f"切片结果文件格式错误: {result_file}")
        return data
    return {}


def _extract_float(text: str) -> Optional[float]:
    match = re.search(r"(-?\d+(?:\.\d+)?)", text)
    return float(match.group(1)) if match else None


def _parse_gcode_metadata(gcode_path: Path) -> Dict[str, Any]:
    metadata: Dict[str, Any] = {}
    patterns = [
        (
            "estimated_weight_grams",
            re.compile(r"^\s*;\s*(?:total\s+)?filament used \[g\]\s*=\s*(.+)$", re.I),
            "float",
        ),
        (
            "estimated_print_time_seconds",
            re.compile(r"^\s*;\s*estimated printing time(?: \(normal mode\))?\s*=\s*(.+)$", re.I),
            "duration",
        ),
        (
            "filament_type",
            re.compile(r"^\s*;\s*filament_type\s*=\s*(.+)$", re.I),
            "string",
        ),
        (
            "generated_by",
            re.compile(r"^\s*;\s*generated by\s+(.+)$", re.I),
            "string",
        ),
        (
            "filament_density",
            re.compile(r"^\s*;\s*filament_density\s*[:=]\s*(.+)$", re.I),
            "float",
        ),
        (
            "filament_diameter",
            re.compile(r"^\s*;\s*filament_diameter\s*[:=]\s*(.+)$", re.I),
            "float",
        ),
    ]

    extrusion_relative = False
    current_e = 0.0
    total_extrusion_mm = 0.0
    max_remaining_minutes: Optional[int] = None

    with gcode_path.open("r", encoding="utf-8", errors="ignore") as handle:
        for line_number, line in enumerate(handle, start=1):
            for key, pattern, value_type in patterns:
                if key in metadata:
                    continue
                match = pattern.search(line)
                if not match:
                    continue
                raw_value = match.group(1).strip()
                if value_type == "float":
                    parsed = _extract_float(raw_value)
                    if parsed is not None:
                        metadata[key] = parsed
                elif value_type == "duration":
                    parsed = _parse_duration_to_seconds(raw_value)
                    if parsed is not None:
                        metadata[key] = parsed
                else:
                    metadata[key] = raw_value

            code = line.split(";", 1)[0].strip()
            if not code:
                if line_number >= 200 and all(key in metadata for key, *_ in patterns[:4]):
                    break
                continue

            if re.search(r"^\s*M82\b", code, re.I):
                extrusion_relative = False
                continue
            if re.search(r"^\s*M83\b", code, re.I):
                extrusion_relative = True
                continue

            if re.search(r"^\s*G92\b", code, re.I):
                e_match = re.search(r"(?:^|\s)E(-?\d+(?:\.\d+)?)", code, re.I)
                if e_match:
                    current_e = float(e_match.group(1))
                continue

            m73_match = re.search(r"^\s*M73\b.*(?:^|\s)R(\d+)\b", code, re.I)
            if m73_match:
                remaining_minutes = int(m73_match.group(1))
                max_remaining_minutes = max(max_remaining_minutes or 0, remaining_minutes)

            if not re.search(r"^\s*G[0-3]\b", code, re.I):
                continue

            e_match = re.search(r"(?:^|\s)E(-?\d+(?:\.\d+)?)", code, re.I)
            if not e_match:
                continue

            extrusion_value = float(e_match.group(1))
            if extrusion_relative:
                delta_e = extrusion_value
            else:
                delta_e = extrusion_value - current_e
                current_e = extrusion_value

            if delta_e > 0:
                total_extrusion_mm += delta_e

    if max_remaining_minutes is not None and "estimated_print_time_seconds" not in metadata:
        metadata["estimated_print_time_seconds"] = max_remaining_minutes * 60

    filament_density = metadata.get("filament_density")
    filament_diameter = metadata.get("filament_diameter")
    if (
        total_extrusion_mm > 0
        and isinstance(filament_density, (int, float))
        and isinstance(filament_diameter, (int, float))
        and filament_density > 0
        and filament_diameter > 0
        and "estimated_weight_grams" not in metadata
    ):
        radius_mm = filament_diameter / 2.0
        cross_section_area_mm2 = math.pi * radius_mm * radius_mm
        volume_mm3 = total_extrusion_mm * cross_section_area_mm2
        metadata["estimated_weight_grams"] = volume_mm3 * filament_density / 1000.0

    if total_extrusion_mm > 0:
        metadata["filament_used_mm"] = total_extrusion_mm

    return metadata


def _guess_extension(model_url: str) -> str:
    parsed = urlparse(model_url)
    suffix = Path(parsed.path).suffix.lower()
    return suffix if suffix else ".stl"


def _detect_extension_from_bytes(model_bytes: bytes, fallback: str) -> str:
    if not model_bytes:
        return fallback
    head = model_bytes[:16]
    # GLB magic header: b'glTF'
    if head.startswith(b"glTF"):
        return ".glb"
    # Basic OBJ hint
    text_head = model_bytes[:256].decode("utf-8", errors="ignore").lstrip().lower()
    if text_head.startswith("v ") or text_head.startswith("o ") or text_head.startswith("#"):
        return ".obj"
    return fallback


async def _download_http_file(model_url: str) -> bytes:
    timeout = aiohttp.ClientTimeout(total=300)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.get(model_url) as response:
            response.raise_for_status()
            return await response.read()


async def load_model_bytes(model_url: str) -> bytes:
    """从本地 uploads、OSS 或外部 URL 读取模型文件。"""
    if not model_url:
        raise PrintSliceError("模型文件地址为空")

    if model_url.startswith("oss://") or model_url.startswith("models/"):
        oss_key = model_url.replace("oss://", "") if model_url.startswith("oss://") else model_url
        data = oss_manager.download_file_bytes(oss_key)
        if not data:
            raise PrintSliceError(f"无法从 OSS 读取模型文件: {oss_key}")
        return data

    if model_url.startswith("/uploads/"):
        upload_path = Path(Config.UPLOAD_DIR) / model_url.removeprefix("/uploads/")
        if not upload_path.exists():
            raise PrintSliceError(f"本地模型文件不存在: {upload_path}")
        return upload_path.read_bytes()

    parsed = urlparse(model_url)
    if parsed.scheme in {"http", "https"}:
        return await _download_http_file(model_url)

    local_path = Path(model_url)
    if local_path.exists():
        return local_path.read_bytes()

    raise PrintSliceError(f"不支持的模型地址: {model_url}")


async def _run_external_slicer(
    input_path: Path,
    output_dir: Path,
    material: str,
    height: str,
) -> tuple[Path, Dict[str, Any]]:
    template = Config.PRINT_SLICER_CMD_TEMPLATE.strip()
    if not template:
        raise PrintSliceError("未配置 PRINT_SLICER_CMD_TEMPLATE")

    command = template.format(
        input_path=shlex.quote(str(input_path)),
        output_dir=shlex.quote(str(output_dir)),
        material=shlex.quote(material),
        height=shlex.quote(height),
        input_name=shlex.quote(input_path.name),
    )

    process = await asyncio.create_subprocess_shell(
        command,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    try:
        stdout, stderr = await asyncio.wait_for(
            process.communicate(),
            timeout=Config.PRINT_SLICER_TIMEOUT_SECONDS,
        )
    except asyncio.TimeoutError as exc:
        process.kill()
        await process.communicate()
        raise PrintSliceError("切片超时") from exc

    if process.returncode != 0:
        raise PrintSliceError(
            f"切片命令执行失败: {stderr.decode('utf-8', errors='ignore') or stdout.decode('utf-8', errors='ignore')}"
        )

    candidates = sorted(output_dir.glob("*.gcode"))
    if not candidates:
        raise PrintSliceError("切片命令执行完成，但未生成 gcode 文件")

    metadata = _load_slice_result_metadata(output_dir)
    if not metadata:
        metadata = _parse_gcode_metadata(candidates[0])
    return candidates[0], metadata


def _write_mock_gcode(output_dir: Path, job_id: str, material: str, height: str) -> Path:
    output_path = output_dir / f"{job_id}.gcode"
    output_path.write_text(
        "\n".join(
            [
                "; MOCK GCODE GENERATED BY ai-soulmate",
                f"; job_id={job_id}",
                f"; material={material}",
                f"; height={height}",
                "G21",
                "G90",
                "M82",
                "G28",
                "G1 Z5 F3000",
                "M84",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return output_path


async def slice_print_model(
    *,
    job_id: str,
    user_id: str,
    model_url: str,
    material: str,
    height: str,
) -> Dict[str, Any]:
    """
    将模型切片为 gcode 并上传到 OSS。
    """
    model_bytes = await load_model_bytes(model_url)
    input_extension = _guess_extension(model_url)
    detected_extension = _detect_extension_from_bytes(model_bytes, input_extension)

    with tempfile.TemporaryDirectory(prefix=f"print-job-{job_id[:8]}-") as temp_dir:
        temp_path = Path(temp_dir)
        input_path = temp_path / f"input{detected_extension}"
        output_dir = temp_path / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        input_path.write_bytes(model_bytes)

        slicer_metadata: Dict[str, Any] = {}
        if Config.PRINT_SLICER_CMD_TEMPLATE.strip():
            gcode_path, slicer_metadata = await _run_external_slicer(input_path, output_dir, material, height)
        elif Config.PRINT_ENABLE_MOCK_SLICER:
            logger.warning("未配置切片命令，当前使用 mock gcode 继续链路联调")
            gcode_path = _write_mock_gcode(output_dir, job_id, material, height)
        else:
            raise PrintSliceError("未配置切片命令，且已禁用 mock slicer")

        gcode_bytes = gcode_path.read_bytes()
        oss_key = f"print-jobs/{user_id}/{job_id}/{gcode_path.name}"
        uploaded_key = oss_manager.upload_object_bytes(oss_key, gcode_bytes)
        if not uploaded_key:
            raise PrintSliceError("gcode 上传 OSS 失败")

        signed_url = oss_manager.generate_presigned_url(uploaded_key, expires=3600)
        return {
            "oss_key": uploaded_key,
            "public_url": signed_url,
            "file_name": _build_client_download_name(job_id, gcode_path.name),
            "file_size": len(gcode_bytes),
            "slicer_metadata": slicer_metadata,
        }
